# services:
#   auth-server:
#     container_name: auth-server
#     image: hyphen01/authserver:v1
#     ports:
#       - "9191:9191"
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/usersdb
#     networks:
#       - auth-network

#   mysql:
#     container_name: mysql-container
#     image: mysql:latest
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=root
#     networks:
#       - auth-network

# networks:
#   auth-network:
#     driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=usersdb
    ports:
      - "3306:3306"
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-server:
    image: hyphen01/authserver:v1
    container_name: auth-server
    ports:
      - "9191:9191"
    depends_on:
      mysql:
        condition: service_healthy # ðŸš€ wait until MySQL is healthy
    networks:
      - auth-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/usersdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092

  kafka:
    container_name: kafka-container
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
