server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:

  config:
    activate:
      on-profile: "dev"
  cloud:
    stream:
      function:
        definition:
    bindings:
      userRegistration-out-0:
        destination: "user-registration"
#    kafka:
#      binder:
#        brokers:
#          - localhost:9092
  application:
    name: authserver
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



logging:
  level:
    org:
      springframework:
        cloud:
          stream: TRACE
        security: DEBUG
